apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.app.name }}
    namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
