---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
