---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.sub_domains }}
  - host: {{ .sub }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .service_name }}
          servicePort: {{ .service_port }}
  {{- end }}


{{- range .Values.ingress.sub_domains }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .cert_name }}
  namespace: {{ $.Values.namespace }}
spec:
  domains:
  - {{ .sub }}
{{- end }}
