name: Validate

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Pull cache
      #   id: cache-python
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: monet-webapp-dependencies-${{ hashFiles('**/base.txt') }}-${{ hashFiles('**/local.txt') }}
      #     restore-keys: |
      #       monet-webapp-dependencies-

      - name: Install dependencies
        run: |
          npm install

      - name: Tests
        run: |
          USE_CHROME=1 npm test
